### ISSUE TITLE
Add auto option for moveIndex transform

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/wilderness-core#21]
Moved from https://github.com/colinmeinke/wilderness/issues/49

**Comment by colinmeinke** [comment]
https://github.com/veltman/flubber

**Comment by dalisoft** [comment]
https://github.com/colinmeinke/points/pull/20

**Comment by dalisoft** [comment]
I not sure what you mean by adding flubber.js here, project bit slow and for simple and less points based shapes. For large shapes fastest is your project (in free)

**Comment by colinmeinke** [comment]
Think I'm going to wait until there is more demand for this.

**Comment by dalisoft** [comment]
Yes. It is not commonly using. I also after a lot using your library want to use manual for better naturality
