### ISSUE TITLE
Combine two library for best result?

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness-core#24]
Hi @colinmeinke. I am in codrops articles see the good project that if combine with wilderness would be awesome. I cant implement to my project because my project is closed source. https://github.com/veltman/flubber

**Comment by colinmeinke** [comment]
Yeah I just saw this yesterday, it looks really cool and for sure there are some things that would be fantastic to get into wilderness. I think wilderness-core vastly improves on wilderness in these areas, so let's see where we're at in the next few weeks when I get the time to merge wilderness and wilderness-core.

**Comment by dalisoft** [comment]
I am want to say if we implement normalise, addpoint, etc to each module like points.js and svgpoints will be great. If need help, i am here

**Comment by dalisoft** [comment]
I seem, your API (old api) works fine on my project, but there flubber has split the non-multi-moveto shapes to parts, that very helpful.

But when it comes to bit large/complex shape just doesn't morphs.

**Comment by dalisoft** [comment]
@colinmeinke I find something, maybe helps to improvements for this project

1) https://bl.ocks.org/veltman/218a162265c772f86bc26c1bc91fe58b
2) https://bl.ocks.org/veltman/4d1413aa5fd3bb5af1a806c146870031

3) Alternative to 2-resource, but slower https://bl.ocks.org/veltman/c582a31d347e04dd75d5331b0074558e
4) https://bl.ocks.org/veltman/949ce9c1b6f3e54c6e18

5) https://github.com/alexjlockwood/ShapeShifter

**Comment by dalisoft** [comment]
Your solution with latest wilderness-core works perfectly, improving this would awesome than this. Can you think merge this to Wilderness?

**Comment by colinmeinke** [comment]
I have some time to work on this now, so I should be merging wilderness core very soon!
